### PR TITLE
Add dependencyOverviewEnabled setting

### PR DESCRIPTION
**Pull request by bcomnes**
This settings lets one disable dependency diff comments in the bot.

### CODE REVIEW

**Comment by feross** [comment]
Can we not expose the "diff" terminology to end users?

I suggest `dependencyOverviewEnabled`

**Review by feross — COMMENTED** [review]
Can we not expose the "diff" terminology to end users?

I suggest `dependencyOverviewEnabled`

**Comment by bcomnes** [comment]
Yeah ok, agreed. Changing.

**Comment by bcomnes** [comment]
Updated.

**Review by voxpelli — APPROVED** [review]

**Pull request merged**
