### PR TITLE
Return 0 value defaults and default values

### PR DESCRIPTION
**Pull request by bcomnes**
This makes it easier downstream where you can assume these things are iterable. Types might still need tweaking, but you get the picture.

### CODE REVIEW

**Review by voxpelli — CHANGES_REQUESTED** [review]
We should update `SocketYmlGitHub` and `SocketYml` to reflect this as well.

Eg. changing ` * @property {string[]} [projectIgnorePaths]` to ` * @property {string[]} projectIgnorePaths`

**Comment by bcomnes** [comment]
Oh I see brackets make it optional.

**Comment by voxpelli** [comment]
But then the `import('ajv').JSONSchemaType<SocketYml>` seems to not match this implementation of the JSON Schema anymore, hmm, I need to sleep on this 😝 

Tired Bored To Death - LTYT5GTIiAMBa

**Comment by bcomnes** [comment]
Does this work?

**Comment by voxpelli** [comment]
@bcomnes Looks like it! I did another little tweak on top of yours to get rid of the `|| {}`, what do you think?

**Comment by bcomnes** [comment]
> @bcomnes Looks like it! I did another little tweak on top of yours to get rid of the `|| {}`, what do you think?

lgtm

**Review by voxpelli — APPROVED** [review]

**Pull request merged**
